// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckModels():Promise<void>;

export function ClearCache():Promise<string>;

export function GetCacheInfo():Promise<Record<string, any>>;

export function GetSettings():Promise<main.AppConfig>;

export function ProcessPaths(arg1:Array<string>):Promise<Array<main.FileItem>>;

export function RunScript(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetSettings(arg1:main.AppConfig):Promise<void>;
