// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckModels() {
  return window['go']['main']['App']['CheckModels']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ProcessPaths(arg1) {
  return window['go']['main']['App']['ProcessPaths'](arg1);
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
